package br.com.fiap.equipment_rent.entity;

import jakarta.persistence.*;
import lombok.*;

//Tells JPA that this is a persistent entity
@Entity

//Define the name of the table
@Table(name = "equipments")

@Getter
@Setter

/*
 * public Equipment(){
 * }
 */
@NoArgsConstructor

/*
 * public Equipment(
 *   Long id,
 *   String name,
 *   String description,
 *   BigDecimal price,
 *   Integer stock,
 *   Boolean active
 * ){}
 */
@AllArgsConstructor

/*
* Equipment equipment = Equipment.builder()
*   .name("Notebook")
*   .description("A")
*   .stock(10)
*   .active(true)
*   .build();
* */
@Builder
@ToString
@EqualsAndHashCode


public class Equipment {

    /*
    * @Id -> Set this attribute as database primary key
    * @GeneratedValue -> The value of id will be automatically generated by DB
    * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
    * @Column -> Let us configure how this attribute will be represented in DB
    * */
    @Column(nullable = false) //Cannot be null
    private String name;

    private String description;

    @Column(nullable = false)
    private int stock;

    @Column(nullable = false)
    private Boolean active;
}
